### ISSUE TITLE
rMView Win64 Exectuable Bundle

### ISSUE THREAD

**Issue by luke4737** [bordaigorl/rmview#74] opened 2021-05-09 11:10 UTC
Hello, i've downloaded the Win64 exectuable bundle and have encountered an issue.
![image](https://user-images.githubusercontent.com/83906801/117569719-f8d64980-b0be-11eb-9822-0745affffc0a.png)

I have entered my devices IP, password and have re-installed several times.

I have factory reset the rM2, connected to the appropiate cloud services and have updated the software to version 2.7.0.51

Has this issue been encountered before?

Thank you for your time

**Comment by bordaigorl** [comment] 2021-05-09 20:09
I think this is a duplicate of #57 
The quick workaround for now is to copy the libcrypto file to the tablet as explained [here](https://github.com/bordaigorl/rmview/issues/57#issuecomment-808193006)

**Closed as completed** 2021-05-18 06:59 UTC
Labels: duplicate
